# vim ft=yaml
# travis-ci.org definition for python-patterns build
language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Disabled for now since cause more pain than gain
#  - "pypy"
#  - "pypy3"

cache:
  - pip

install:
  - travis_retry pip install -q coveralls codecov six
  - pip install flake8  # eventually worth

script:
  # Run tests
  - PYTHONPATH=. nosetests -s -v --with-doctest --with-cov --cover-package . --logging-level=INFO -v .
  # Actually run all the scripts, contributing to coverage
  - PYTHONPATH=. ./run_all.sh
  - flake8 *py

after_success:
  - coveralls
  - codecov
