name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip
      - run: pip install black codespell flake8 isort pytest pyupgrade tox
      - run: black --check . || true
      - run: codespell --quiet-level=2  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --show-source --statistics
      - run: isort --profile black .
      - run: tox
      - run: pip install -e .
      - run: pytest .
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
